### ISSUE TITLE
Health Check Failing for Proxy

### ISSUE THREAD

**Issue by TropicalShadow** [jeremylvln/Shulker#387]
### What happened?

Health check is failing due to ping description structure changes in 1.20.3

`failed to ping localhost:25577 : json: cannot unmarshal string into Go struct field ServerInfo.description of type mcpinger.RegularChatComponent`

I believe this is related to [mc-monitor issue (78)](https://github.com/itzg/mc-monitor/pull/78)
Due to using a static old version of itzg/bungeecord image [here](https://github.com/jeremylvln/Shulker/blob/7d96f9b423a859c4857ab6b94229df857e563056/packages/shulker-operator/src/reconcilers/proxy_fleet/fleet.rs#L50) `const PROXY_IMAGE: &str = "itzg/bungeecord:java17-2022.4.1";`

### Version

v0.6.1

### Kubernetes Version

v1.28.3

### Relevant log output

```Shell
bungeecord@velocity-kxwdg-wdn5f:~$ mc-monitor status --host localhost --port 25577
failed to ping localhost:25577 : json: cannot unmarshal string into Go struct field ServerInfo.description of type mcpinger.RegularChatComponent
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TropicalShadow** [comment]
The issue has been fixed in mc-monitor, and is await to be updated in docker-bungeecord https://github.com/itzg/docker-bungeecord/issues/165

**Comment by jeremylvln** [comment]
Hi,

I dug a lot to understand where the problem was. The issue was your MOTD itself that was invalid. It was producing an invalid `TextComponent` (see the red arrow pointing to an empty string rather than a valid JSON component). I'm unsure why tho... is it Adventure's fault, or Velocity's... I don't know.

<img width="982" alt="image" src="https://github.com/jeremylvln/Shulker/assets/6763873/b7aef25d-3dfd-4c2d-89f6-88e62b9f7f2f">

But I've fixed it by changing your MOTD (considering it was the same as the other issue) by moving the spaces before/after the lightning bolt inside the `<red>` tags:

```yaml
config:
  motd: <red>▓▒░             ⚡   </red><gradient:red:blue><bold>BridgeSplash</bold></gradient><red>   ⚡             ░▒▓</red>
```

**Comment by TropicalShadow** [comment]
I managed to get it working with the latest version of docker-bungeecord so I assume my broken minimessage config no longer breaks in the latest version.

Would it be worth considering updating to the latest for convenience and support for Java 21?
is there any reason to remain in the `java17-2022.4.1` version of docker bungeecord?

**Comment by jeremylvln** [comment]
> I managed to get it working with the latest version of docker-bungeecord so I assume my broken minimessage config no longer breaks in the latest version.
> 
> Would it be worth considering updating to the latest for convenience and support for Java 21? is there any reason to remain in the `java17-2022.4.1` version of docker bungeecord?

There is no particular reason, I just forget to keep them up to date. I've upgraded the images in my last PR, but it was still broken with the MOTD. It's really weird that it succeeded with you... (note that I kept the Java 17 variant, no particular reason I might move to 21 if it works)

**Comment by TropicalShadow** [comment]
I might have changed the MOTD from the previous one I gave you but I was still getting the error presented in the initial report, I found mc-monitor was having issues pinging correctly (in docker-bungeecord), so I did some digging and found that docker-bungeecord wasn't using the latest version of mc-monitor, I sent a pull-request to update mc-monitor in docker-bungeecord and that fixed the pinging structure description issue I was having.

**Comment by jeremylvln** [comment]
Oh, I see your commit, but they didn't publish a new release, that's why the issue is not solved even if I took the latest version (which is 2023.11.0 - so a bit old still).

**Comment by TropicalShadow** [comment]
i don't think they are pushing to github anymore, i looked on docker hub and found it was getting updated there tho

**Comment by jeremylvln** [comment]
Hmm. They are not publishing `javaXX-XXXXXX` tags anymore, just the Java versions. That's unfortunate but ok

**Comment by TropicalShadow** [comment]
not sure if I am seeing this wrong but it seems they are still doing Java versions

https://hub.docker.com/r/itzg/minecraft-server/tags

[Java 17](https://hub.docker.com/layers/itzg/minecraft-server/2024.2.1-java17-openj9/images/sha256-481d4e6534aeb0dad72a74e650e1886ed9dd067dd4c0950e2204a88b55d97f92?context=explore)

[Java 11](https://hub.docker.com/layers/itzg/minecraft-server/2024.2.1-java11/images/sha256-27cbfe60a721861ae757c414d8a1cd2f4917431ae6195d65138e4a6daba65d04?context=explore)

**Comment by jeremylvln** [comment]
Yes they do, but I prefer using specific version tags (`java17-2024.02.01` over `java17` for instance). Too many times in the past, my apps broke suddenly do to a poisoned release. I've asked itzg to create a Git tag (which triggers a proper release automatically).

He is quite reactive, so I think it will be fixed quickly.

**Comment by TropicalShadow** [comment]
ah understandable, much appreciated. Thank you for working through these changes

**Comment by jeremylvln** [comment]
Wow, he was really fast! I've opened a PR to bump the image: https://github.com/jeremylvln/Shulker/pull/397

**Comment by jeremylvln** [comment]
Everything if merged, including the bump in the BungeeCord image. I started a proper release, let me know if your issue is fixed :)

**Comment by TropicalShadow** [comment]
hi, sorry for the late response, this seems to have been cleared up and fixed. thank you
